# These are supported funding model platforms

github: [AtsuPager]
custom: ["https://www.blockchain.com/btc/address/bc1qcyk460u3t3fh0n4t0rqdjmwrzx89flgrfpgcet", "https://etherscan.io/address/0x517a367a8Bcc2C5E7e2Eb98D8b40305Ba1706529"]
